#pragma once
#include <unordered_map>
#include <string>
#include <cstdint>

inline const std::unordered_map<uint32_t, std::string> effectNames = {
    { 2,  "Paralyze" },
    { 19, "Slow"     },
    { 31, "Silence"  },
    { 34, "Blind"    },
    { 39, "Petrify"  },
    { 43, "Poison"   },
    { 50, "Curse"    },
    { 52, "Disease"  },
    { 57, "Bind"     },
    { 66, "Sleep"    },
    { 69, "Stun"     },
    { 71, "Amnesia"  },
    { 74, "Charm"    },
    { 79, "Gravity"  },
    { 83, "Slow II"  },
    { 84, "Sleep II" },
    { 92, "Bind II"  },
    { 95, "Petrify II"},
    { 101,"Curse II" },
    { 109,"Doom"     },
    { 113,"Break"    },
    { 114,"Addle"    },
    { 119,"Frost"    },
    { 120,"Burn"     },
    { 121,"Choke"    },
    { 122,"Rasp"     },
    { 123,"Shock"    },
    { 124,"Drown"    },
    { 130,"Plague"   },
    { 137,"Silence II"},
    { 138,"Blind II" },
    { 139,"Poison II"},
    { 140,"Disease II"},
    { 150,"Curse III"},
    { 169,"Bind III" },
    { 175,"Petrify III"},
    { 179,"Sleep III"},
    { 180,"Slow III" },
    { 185,"Stun II"  },
    { 200,"Amnesia II"},
    { 205,"Charm II" },
    { 210,"Gravity II"},
    { 222,"Doom II"  },
    { 230,"Break II" },
    { 231,"Addle II" },
    { 250,"Frost II" },
    { 251,"Burn II"  },
    { 252,"Choke II" },
    { 253,"Rasp II"  },
    { 254,"Shock II" },
    { 255,"Drown II" },
    { 260,"Plague II"}
    // add more IDs from bufftable.lua
};
