namespace CurePlease
{
    partial class Form2
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form2));
            this.button4 = new System.Windows.Forms.Button();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.recastSongs_monitored = new System.Windows.Forms.CheckBox();
            this.GEO_engaged = new System.Windows.Forms.CheckBox();
            this.GeoAOE_Engaged = new System.Windows.Forms.CheckBox();
            this.label3 = new System.Windows.Forms.Label();
            this.naSpellsenable = new System.Windows.Forms.CheckBox();
            this.naErase = new System.Windows.Forms.CheckBox();
            this.Esuna = new System.Windows.Forms.CheckBox();
            this.EsunaOnlyAmnesia = new System.Windows.Forms.CheckBox();
            this.curagaPercentageValueLabel = new System.Windows.Forms.Label();
            this.curagaCurePercentage = new System.Windows.Forms.TrackBar();
            this.label30 = new System.Windows.Forms.Label();
            this.curaga5Amount = new System.Windows.Forms.NumericUpDown();
            this.curaga4Amount = new System.Windows.Forms.NumericUpDown();
            this.curaga3Amount = new System.Windows.Forms.NumericUpDown();
            this.curaga2Amount = new System.Windows.Forms.NumericUpDown();
            this.curagaAmount = new System.Windows.Forms.NumericUpDown();
            this.monitoredCurePercentage = new System.Windows.Forms.TrackBar();
            this.label55 = new System.Windows.Forms.Label();
            this.monitoredCurePercentageValueLabel = new System.Windows.Forms.Label();
            this.fullCureenabled = new System.Windows.Forms.CheckBox();
            this.fullCureamount = new System.Windows.Forms.NumericUpDown();
            this.priorityCurePercentage = new System.Windows.Forms.TrackBar();
            this.priorityCurePercentageLabel = new System.Windows.Forms.Label();
            this.cure6amount = new System.Windows.Forms.NumericUpDown();
            this.priorityCurePercentageValueLabel = new System.Windows.Forms.Label();
            this.cure5amount = new System.Windows.Forms.NumericUpDown();
            this.curePercentage = new System.Windows.Forms.TrackBar();
            this.cure4amount = new System.Windows.Forms.NumericUpDown();
            this.curePercentageValueLabel = new System.Windows.Forms.Label();
            this.cure3amount = new System.Windows.Forms.NumericUpDown();
            this.curePercentageLabel = new System.Windows.Forms.Label();
            this.cure2amount = new System.Windows.Forms.NumericUpDown();
            this.cure1amount = new System.Windows.Forms.NumericUpDown();
            this.label64 = new System.Windows.Forms.Label();
            this.label65 = new System.Windows.Forms.Label();
            this.label22 = new System.Windows.Forms.Label();
            this.label23 = new System.Windows.Forms.Label();
            this.label19 = new System.Windows.Forms.Label();
            this.label20 = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.label17 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.autoRefreshLabel = new System.Windows.Forms.Label();
            this.EnlightenmentReraise = new System.Windows.Forms.CheckBox();
            this.perpetuanceRegen = new System.Windows.Forms.CheckBox();
            this.accessionProShell = new System.Windows.Forms.CheckBox();
            this.accessionRegen = new System.Windows.Forms.CheckBox();
            this.entrustSpell_target = new System.Windows.Forms.TextBox();
            this.GEOSpell_target = new System.Windows.Forms.TextBox();
            this.marcato = new System.Windows.Forms.CheckBox();
            this.FullCircleBox = new System.Windows.Forms.CheckBox();
            this.DematerializeBox = new System.Windows.Forms.CheckBox();
            this.EntrustBox = new System.Windows.Forms.CheckBox();
            this.convert = new System.Windows.Forms.CheckBox();
            this.divineSealBox = new System.Windows.Forms.CheckBox();
            this.groupBox16 = new CurePlease.GroupBoxEx();
            this.AssistSpecifiedTarget = new System.Windows.Forms.CheckBox();
            this.label8 = new System.Windows.Forms.Label();
            this.autoTarget_target = new System.Windows.Forms.TextBox();
            this.label37 = new System.Windows.Forms.Label();
            this.label36 = new System.Windows.Forms.Label();
            this.Hate_SpellType = new System.Windows.Forms.ComboBox();
            this.autoTarget = new System.Windows.Forms.CheckBox();
            this.autoTargetSpell = new System.Windows.Forms.TextBox();
            this.DevotionTargetName = new System.Windows.Forms.TextBox();
            this.DevotionTargetType = new System.Windows.Forms.ComboBox();
            this.label34 = new System.Windows.Forms.Label();
            this.enableOutOfPartyHealing = new System.Windows.Forms.CheckBox();
            this.enableMonitoredPriority = new System.Windows.Forms.CheckBox();
            this.Undercure = new System.Windows.Forms.CheckBox();
            this.Overcure = new System.Windows.Forms.CheckBox();
            this.healWhenMPBelow = new System.Windows.Forms.NumericUpDown();
            this.label9 = new System.Windows.Forms.Label();
            this.standAtMP_Percentage = new System.Windows.Forms.NumericUpDown();
            this.standAtMP = new System.Windows.Forms.CheckBox();
            this.healLowMP = new System.Windows.Forms.CheckBox();
            this.label5 = new System.Windows.Forms.Label();
            this.mpMintempitemusage = new System.Windows.Forms.NumericUpDown();
            this.listeningPort = new System.Windows.Forms.TextBox();
            this.label48 = new System.Windows.Forms.Label();
            this.ipAddress = new System.Windows.Forms.TextBox();
            this.label38 = new System.Windows.Forms.Label();
            this.FFXIDefaultAutoFollow = new System.Windows.Forms.CheckBox();
            this.saveAsButton = new System.Windows.Forms.Button();
            this.loadButton = new System.Windows.Forms.Button();
            this.loadJobSettings = new System.Windows.Forms.CheckBox();
            this.openFileDialog1 = new System.Windows.Forms.OpenFileDialog();
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.tabPage7 = new System.Windows.Forms.TabPage();
            this.groupBoxEx1 = new CurePlease.GroupBoxEx();
            this.panel15 = new System.Windows.Forms.Panel();
            this.label67 = new System.Windows.Forms.Label();
            this.enableHotKeys = new System.Windows.Forms.CheckBox();
            this.groupBox18 = new CurePlease.GroupBoxEx();
            this.groupBox17 = new CurePlease.GroupBoxEx();
            this.label61 = new System.Windows.Forms.Label();
            this.trackCastingPackets = new System.Windows.Forms.CheckBox();
            this.label24 = new System.Windows.Forms.Label();
            this.enableFastCast_Mode = new System.Windows.Forms.CheckBox();
            this.groupBox14 = new CurePlease.GroupBoxEx();
            this.panel9 = new System.Windows.Forms.Panel();
            this.label56 = new System.Windows.Forms.Label();
            this.autoFollow_Warning = new System.Windows.Forms.CheckBox();
            this.checkBox4 = new System.Windows.Forms.CheckBox();
            this.autoFollowName = new System.Windows.Forms.TextBox();
            this.autoFollowDistance = new System.Windows.Forms.NumericUpDown();
            this.label33 = new System.Windows.Forms.Label();
            this.label32 = new System.Windows.Forms.Label();
            this.groupBox13 = new CurePlease.GroupBoxEx();
            this.pauseOnKO = new System.Windows.Forms.CheckBox();
            this.MinimiseonStart = new System.Windows.Forms.CheckBox();
            this.pauseOnStartBox = new System.Windows.Forms.CheckBox();
            this.pauseOnZoneBox = new System.Windows.Forms.CheckBox();
            this.tabPage5 = new System.Windows.Forms.TabPage();
            this.groupBox10 = new CurePlease.GroupBoxEx();
            this.label59 = new System.Windows.Forms.Label();
            this.TargetRemoval_Delay = new System.Windows.Forms.NumericUpDown();
            this.label58 = new System.Windows.Forms.Label();
            this.DisableTargettingCancel = new System.Windows.Forms.CheckBox();
            this.groupBox36 = new CurePlease.GroupBoxEx();
            this.label27 = new System.Windows.Forms.Label();
            this.RadialArcanaSpell = new System.Windows.Forms.ComboBox();
            this.label11 = new System.Windows.Forms.Label();
            this.RadialArcanaMP = new System.Windows.Forms.NumericUpDown();
            this.Fullcircle_GEOTarget = new System.Windows.Forms.CheckBox();
            this.Fullcircle_DisableEnemy = new System.Windows.Forms.CheckBox();
            this.groupBox15 = new CurePlease.GroupBoxEx();
            this.DevotionWhenEngaged = new System.Windows.Forms.CheckBox();
            this.label35 = new System.Windows.Forms.Label();
            this.DevotionMP = new System.Windows.Forms.NumericUpDown();
            this.Raise = new CurePlease.GroupBoxEx();
            this.acceptRaiseOnlyWhenNotInCombat = new System.Windows.Forms.CheckBox();
            this.acceptRaise = new System.Windows.Forms.CheckBox();
            this.groupBox33 = new CurePlease.GroupBoxEx();
            this.label25 = new System.Windows.Forms.Label();
            this.enableAddOn = new System.Windows.Forms.CheckBox();
            this.groupBox32 = new CurePlease.GroupBoxEx();
            this.OvercureOnHighPriority = new System.Windows.Forms.CheckBox();
            this.groupBox29 = new CurePlease.GroupBoxEx();
            this.label51 = new System.Windows.Forms.Label();
            this.sublimationMP = new System.Windows.Forms.NumericUpDown();
            this.groupBox11 = new CurePlease.GroupBoxEx();
            this.label26 = new System.Windows.Forms.Label();
            this.ConvertMP = new System.Windows.Forms.NumericUpDown();
            this.groupBox4 = new CurePlease.GroupBoxEx();
            this.lowMPcheckBox = new System.Windows.Forms.CheckBox();
            this.label4 = new System.Windows.Forms.Label();
            this.mpMinCastValue = new System.Windows.Forms.NumericUpDown();
            this.tabPage3 = new System.Windows.Forms.TabPage();
            this.groupBox24 = new CurePlease.GroupBoxEx();
            this.troubadour = new System.Windows.Forms.CheckBox();
            this.nightingale = new System.Windows.Forms.CheckBox();
            this.pianissimo = new System.Windows.Forms.CheckBox();
            this.groupBox8 = new CurePlease.GroupBoxEx();
            this.LifeCycleBox = new System.Windows.Forms.CheckBox();
            this.EclipticAttritionBox = new System.Windows.Forms.CheckBox();
            this.RadialArcanaBox = new System.Windows.Forms.CheckBox();
            this.BlazeOfGloryBox = new System.Windows.Forms.CheckBox();
            this.rdmJAgroup = new CurePlease.GroupBoxEx();
            this.composure = new System.Windows.Forms.CheckBox();
            this.schJAgroup = new CurePlease.GroupBoxEx();
            this.addBlack = new System.Windows.Forms.CheckBox();
            this.darkArts = new System.Windows.Forms.CheckBox();
            this.sublimation = new System.Windows.Forms.CheckBox();
            this.perpetuance = new System.Windows.Forms.CheckBox();
            this.rapture = new System.Windows.Forms.CheckBox();
            this.accession = new System.Windows.Forms.CheckBox();
            this.celerity = new System.Windows.Forms.CheckBox();
            this.penury = new System.Windows.Forms.CheckBox();
            this.addWhite = new System.Windows.Forms.CheckBox();
            this.lightArts = new System.Windows.Forms.CheckBox();
            this.whmJAgroup = new CurePlease.GroupBoxEx();
            this.DivineCaressBox = new System.Windows.Forms.CheckBox();
            this.DevotionBox = new System.Windows.Forms.CheckBox();
            this.afflatusMisery = new System.Windows.Forms.CheckBox();
            this.afflatusSolace = new System.Windows.Forms.CheckBox();
            this.tabPage8 = new System.Windows.Forms.TabPage();
            this.SongsOnlyWhenNearEngaged = new System.Windows.Forms.CheckBox();
            this.enableSinging = new System.Windows.Forms.CheckBox();
            this.label40 = new System.Windows.Forms.Label();
            this.recastSong = new System.Windows.Forms.NumericUpDown();
            this.label39 = new System.Windows.Forms.Label();
            this.panel7 = new System.Windows.Forms.Panel();
            this.panel8 = new System.Windows.Forms.Panel();
            this.groupBox30 = new CurePlease.GroupBoxEx();
            this.comboBox3 = new System.Windows.Forms.ComboBox();
            this.label53 = new System.Windows.Forms.Label();
            this.comboBox4 = new System.Windows.Forms.ComboBox();
            this.label54 = new System.Windows.Forms.Label();
            this.groupBox31 = new CurePlease.GroupBoxEx();
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            this.label49 = new System.Windows.Forms.Label();
            this.comboBox2 = new System.Windows.Forms.ComboBox();
            this.label52 = new System.Windows.Forms.Label();
            this.groupBox28 = new CurePlease.GroupBoxEx();
            this.label50 = new System.Windows.Forms.Label();
            this.groupBox20 = new CurePlease.GroupBoxEx();
            this.song3 = new System.Windows.Forms.ComboBox();
            this.dummy1 = new System.Windows.Forms.ComboBox();
            this.label43 = new System.Windows.Forms.Label();
            this.label44 = new System.Windows.Forms.Label();
            this.groupBox23 = new CurePlease.GroupBoxEx();
            this.clarionSong = new System.Windows.Forms.ComboBox();
            this.label47 = new System.Windows.Forms.Label();
            this.groupBox22 = new CurePlease.GroupBoxEx();
            this.song4 = new System.Windows.Forms.ComboBox();
            this.dummy2 = new System.Windows.Forms.ComboBox();
            this.label42 = new System.Windows.Forms.Label();
            this.label41 = new System.Windows.Forms.Label();
            this.groupBox21 = new CurePlease.GroupBoxEx();
            this.song2 = new System.Windows.Forms.ComboBox();
            this.label46 = new System.Windows.Forms.Label();
            this.groupBox19 = new CurePlease.GroupBoxEx();
            this.song1 = new System.Windows.Forms.ComboBox();
            this.label45 = new System.Windows.Forms.Label();
            this.tabPage6 = new System.Windows.Forms.TabPage();
            this.specifiedEngageTarget = new System.Windows.Forms.CheckBox();
            this.EnableLuopanSpells = new System.Windows.Forms.CheckBox();
            this.EnableGeoSpells = new System.Windows.Forms.CheckBox();
            this.groupBox7 = new CurePlease.GroupBoxEx();
            this.label7 = new System.Windows.Forms.Label();
            this.entrustINDISpell = new System.Windows.Forms.ListBox();
            this.groupBox6 = new CurePlease.GroupBoxEx();
            this.label6 = new System.Windows.Forms.Label();
            this.GEOSpell = new System.Windows.Forms.ListBox();
            this.groupBox5 = new CurePlease.GroupBoxEx();
            this.INDISpell = new System.Windows.Forms.ListBox();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.tabControl2 = new System.Windows.Forms.TabControl();
            this.tabPage9 = new System.Windows.Forms.TabPage();
            this.groupBox34 = new CurePlease.GroupBoxEx();
            this.plUtsusemi = new System.Windows.Forms.CheckBox();
            this.groupBox9 = new CurePlease.GroupBoxEx();
            this.AOE_Barstatus = new System.Windows.Forms.CheckBox();
            this.AOE_Barelemental = new System.Windows.Forms.CheckBox();
            this.plAuspice = new System.Windows.Forms.CheckBox();
            this.plBarStatus_Spell = new System.Windows.Forms.ComboBox();
            this.plGainBoost = new System.Windows.Forms.CheckBox();
            this.plBarStatus = new System.Windows.Forms.CheckBox();
            this.plGainBoost_spell = new System.Windows.Forms.ComboBox();
            this.plBarElement_Spell = new System.Windows.Forms.ComboBox();
            this.plBarElement = new System.Windows.Forms.CheckBox();
            this.plProtectralevel = new System.Windows.Forms.NumericUpDown();
            this.plShellra = new System.Windows.Forms.CheckBox();
            this.plShellralevel = new System.Windows.Forms.NumericUpDown();
            this.plProtectra = new System.Windows.Forms.CheckBox();
            this.groupBox1 = new CurePlease.GroupBoxEx();
            this.label68 = new System.Windows.Forms.Label();
            this.autoAdloquium_Minutes = new System.Windows.Forms.NumericUpDown();
            this.label69 = new System.Windows.Forms.Label();
            this.label63 = new System.Windows.Forms.Label();
            this.autoStorm = new System.Windows.Forms.ComboBox();
            this.autoStormspellMinutes = new System.Windows.Forms.NumericUpDown();
            this.label21 = new System.Windows.Forms.Label();
            this.autoRegen = new System.Windows.Forms.ComboBox();
            this.autoRegen_Minutes = new System.Windows.Forms.NumericUpDown();
            this.label18 = new System.Windows.Forms.Label();
            this.autoProtect = new System.Windows.Forms.ComboBox();
            this.autoProtect_Minutes = new System.Windows.Forms.NumericUpDown();
            this.label15 = new System.Windows.Forms.Label();
            this.autoShell = new System.Windows.Forms.ComboBox();
            this.autoShell_Minutes = new System.Windows.Forms.NumericUpDown();
            this.label14 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.autoRefresh = new System.Windows.Forms.ComboBox();
            this.autoRefresh_Minutes = new System.Windows.Forms.NumericUpDown();
            this.autoPhalanxIIMinutes = new System.Windows.Forms.NumericUpDown();
            this.autoHasteMinutes = new System.Windows.Forms.NumericUpDown();
            this.autoPhalanxIILabel = new System.Windows.Forms.Label();
            this.autoHasteLabel = new System.Windows.Forms.Label();
            this.plBuffGroup = new CurePlease.GroupBoxEx();
            this.plSpikes_Spell = new System.Windows.Forms.ComboBox();
            this.plSpikes = new System.Windows.Forms.CheckBox();
            this.panel14 = new System.Windows.Forms.Panel();
            this.plHaste = new System.Windows.Forms.CheckBox();
            this.plHasteLevel1 = new System.Windows.Forms.RadioButton();
            this.plHasteLevel2 = new System.Windows.Forms.RadioButton();
            this.panel12 = new System.Windows.Forms.Panel();
            this.plRegenLevel5 = new System.Windows.Forms.RadioButton();
            this.plRegen = new System.Windows.Forms.CheckBox();
            this.plRegenLevel1 = new System.Windows.Forms.RadioButton();
            this.plRegenLevel4 = new System.Windows.Forms.RadioButton();
            this.plRegenLevel2 = new System.Windows.Forms.RadioButton();
            this.plRegenLevel3 = new System.Windows.Forms.RadioButton();
            this.plAdloquium = new System.Windows.Forms.CheckBox();
            this.plShell = new System.Windows.Forms.CheckBox();
            this.plProtect = new System.Windows.Forms.CheckBox();
            this.plAquaveil = new System.Windows.Forms.CheckBox();
            this.plStormSpell_Spell = new System.Windows.Forms.ComboBox();
            this.plStormSpell = new System.Windows.Forms.CheckBox();
            this.plKlimaform = new System.Windows.Forms.CheckBox();
            this.plEnspell_spell = new System.Windows.Forms.ComboBox();
            this.plEnspell = new System.Windows.Forms.CheckBox();
            this.panel5 = new System.Windows.Forms.Panel();
            this.plTemper = new System.Windows.Forms.CheckBox();
            this.plTemperLevel1 = new System.Windows.Forms.RadioButton();
            this.plTemperLevel2 = new System.Windows.Forms.RadioButton();
            this.panel4 = new System.Windows.Forms.Panel();
            this.plRefresh = new System.Windows.Forms.CheckBox();
            this.plRefreshLevel3 = new System.Windows.Forms.RadioButton();
            this.plRefreshLevel1 = new System.Windows.Forms.RadioButton();
            this.plRefreshLevel2 = new System.Windows.Forms.RadioButton();
            this.plPhalanx = new System.Windows.Forms.CheckBox();
            this.panel3 = new System.Windows.Forms.Panel();
            this.plReraise = new System.Windows.Forms.CheckBox();
            this.plReraiseLevel1 = new System.Windows.Forms.RadioButton();
            this.plReraiseLevel4 = new System.Windows.Forms.RadioButton();
            this.plReraiseLevel2 = new System.Windows.Forms.RadioButton();
            this.plReraiseLevel3 = new System.Windows.Forms.RadioButton();
            this.plBlink = new System.Windows.Forms.CheckBox();
            this.plStoneskin = new System.Windows.Forms.CheckBox();
            this.tabPage10 = new System.Windows.Forms.TabPage();
            this.groupBox27 = new CurePlease.GroupBoxEx();
            this.panel13 = new System.Windows.Forms.Panel();
            this.label66 = new System.Windows.Forms.Label();
            this.regenPerpetuance = new System.Windows.Forms.CheckBox();
            this.regenAccession = new System.Windows.Forms.CheckBox();
            this.adloquiumPerpetuance = new System.Windows.Forms.CheckBox();
            this.adloquiumAccession = new System.Windows.Forms.CheckBox();
            this.barstatusPerpetuance = new System.Windows.Forms.CheckBox();
            this.barspellPerpetuance = new System.Windows.Forms.CheckBox();
            this.aquaveilPerpetuance = new System.Windows.Forms.CheckBox();
            this.stormspellPerpetuance = new System.Windows.Forms.CheckBox();
            this.enspellPerpetuance = new System.Windows.Forms.CheckBox();
            this.stoneskinPerpetuance = new System.Windows.Forms.CheckBox();
            this.phalanxPerpetuance = new System.Windows.Forms.CheckBox();
            this.blinkPerpetuance = new System.Windows.Forms.CheckBox();
            this.refreshPerpetuance = new System.Windows.Forms.CheckBox();
            this.barstatusAccession = new System.Windows.Forms.CheckBox();
            this.barspellAccession = new System.Windows.Forms.CheckBox();
            this.refreshAccession = new System.Windows.Forms.CheckBox();
            this.aquaveilAccession = new System.Windows.Forms.CheckBox();
            this.stormspellAccession = new System.Windows.Forms.CheckBox();
            this.enspellAccession = new System.Windows.Forms.CheckBox();
            this.phalanxAccession = new System.Windows.Forms.CheckBox();
            this.blinkAccession = new System.Windows.Forms.CheckBox();
            this.stoneskinAccession = new System.Windows.Forms.CheckBox();
            this.groupBox26 = new CurePlease.GroupBoxEx();
            this.groupBox25 = new CurePlease.GroupBoxEx();
            this.accessionCure = new System.Windows.Forms.CheckBox();
            this.tabPage4 = new System.Windows.Forms.TabPage();
            this.label57 = new System.Windows.Forms.Label();
            this.panel10 = new System.Windows.Forms.Panel();
            this.panel11 = new System.Windows.Forms.Panel();
            this.na_MagicDefenseDown = new System.Windows.Forms.CheckBox();
            this.na_Weight = new System.Windows.Forms.CheckBox();
            this.na_VitDown = new System.Windows.Forms.CheckBox();
            this.na_Threnody = new System.Windows.Forms.CheckBox();
            this.na_Slow = new System.Windows.Forms.CheckBox();
            this.na_Shock = new System.Windows.Forms.CheckBox();
            this.na_StrDown = new System.Windows.Forms.CheckBox();
            this.na_Requiem = new System.Windows.Forms.CheckBox();
            this.na_Rasp = new System.Windows.Forms.CheckBox();
            this.na_MaxTpDown = new System.Windows.Forms.CheckBox();
            this.na_MaxMpDown = new System.Windows.Forms.CheckBox();
            this.na_MaxHpDown = new System.Windows.Forms.CheckBox();
            this.na_MagicAttackDown = new System.Windows.Forms.CheckBox();
            this.na_MagicAccDown = new System.Windows.Forms.CheckBox();
            this.na_MndDown = new System.Windows.Forms.CheckBox();
            this.na_IntDown = new System.Windows.Forms.CheckBox();
            this.na_Helix = new System.Windows.Forms.CheckBox();
            this.na_Frost = new System.Windows.Forms.CheckBox();
            this.na_EvasionDown = new System.Windows.Forms.CheckBox();
            this.na_Elegy = new System.Windows.Forms.CheckBox();
            this.na_Drown = new System.Windows.Forms.CheckBox();
            this.na_Dia = new System.Windows.Forms.CheckBox();
            this.na_DefenseDown = new System.Windows.Forms.CheckBox();
            this.na_DexDown = new System.Windows.Forms.CheckBox();
            this.na_Choke = new System.Windows.Forms.CheckBox();
            this.na_ChrDown = new System.Windows.Forms.CheckBox();
            this.na_Burn = new System.Windows.Forms.CheckBox();
            this.na_Bio = new System.Windows.Forms.CheckBox();
            this.na_Bind = new System.Windows.Forms.CheckBox();
            this.na_AttackDown = new System.Windows.Forms.CheckBox();
            this.na_Addle = new System.Windows.Forms.CheckBox();
            this.na_AccuracyDown = new System.Windows.Forms.CheckBox();
            this.na_AgiDown = new System.Windows.Forms.CheckBox();
            this.PrioritiseOverLowerTier = new System.Windows.Forms.CheckBox();
            this.SpecifiednaSpellsenable = new System.Windows.Forms.CheckBox();
            this.panel6 = new System.Windows.Forms.Panel();
            this.naBlindness = new System.Windows.Forms.CheckBox();
            this.naPoison = new System.Windows.Forms.CheckBox();
            this.naDisease = new System.Windows.Forms.CheckBox();
            this.naParalysis = new System.Windows.Forms.CheckBox();
            this.naPetrification = new System.Windows.Forms.CheckBox();
            this.naSilence = new System.Windows.Forms.CheckBox();
            this.naCurse = new System.Windows.Forms.CheckBox();
            this.naPlague = new System.Windows.Forms.CheckBox();
            this.plDoomEnabled = new System.Windows.Forms.CheckBox();
            this.plDoomitem = new System.Windows.Forms.ComboBox();
            this.wakeSleepSpell = new System.Windows.Forms.ComboBox();
            this.plSilenceItem = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.monitoredAmnesia = new System.Windows.Forms.CheckBox();
            this.monitoredDisease = new System.Windows.Forms.CheckBox();
            this.monitoredWeight = new System.Windows.Forms.CheckBox();
            this.monitoredVitDown = new System.Windows.Forms.CheckBox();
            this.monitoredThrenody = new System.Windows.Forms.CheckBox();
            this.monitoredSlow = new System.Windows.Forms.CheckBox();
            this.monitoredSleep2 = new System.Windows.Forms.CheckBox();
            this.monitoredSleep = new System.Windows.Forms.CheckBox();
            this.monitoredSilence = new System.Windows.Forms.CheckBox();
            this.monitoredShock = new System.Windows.Forms.CheckBox();
            this.monitoredStrDown = new System.Windows.Forms.CheckBox();
            this.monitoredRequiem = new System.Windows.Forms.CheckBox();
            this.monitoredRasp = new System.Windows.Forms.CheckBox();
            this.monitoredPoison = new System.Windows.Forms.CheckBox();
            this.monitoredPlague = new System.Windows.Forms.CheckBox();
            this.monitoredPetrification = new System.Windows.Forms.CheckBox();
            this.monitoredParalysis = new System.Windows.Forms.CheckBox();
            this.monitoredMaxTpDown = new System.Windows.Forms.CheckBox();
            this.monitoredMaxMpDown = new System.Windows.Forms.CheckBox();
            this.monitoredMaxHpDown = new System.Windows.Forms.CheckBox();
            this.monitoredMagicAtkDown = new System.Windows.Forms.CheckBox();
            this.monitoredMagicAccDown = new System.Windows.Forms.CheckBox();
            this.monitoredMndDown = new System.Windows.Forms.CheckBox();
            this.monitoredIntDown = new System.Windows.Forms.CheckBox();
            this.monitoredHelix = new System.Windows.Forms.CheckBox();
            this.monitoredFrost = new System.Windows.Forms.CheckBox();
            this.monitoredFlash = new System.Windows.Forms.CheckBox();
            this.monitoredEvasionDown = new System.Windows.Forms.CheckBox();
            this.monitoredElegy = new System.Windows.Forms.CheckBox();
            this.monitoredDrown = new System.Windows.Forms.CheckBox();
            this.monitoredDoom = new System.Windows.Forms.CheckBox();
            this.monitoredDia = new System.Windows.Forms.CheckBox();
            this.monitoredDefenseDown = new System.Windows.Forms.CheckBox();
            this.monitoredDexDown = new System.Windows.Forms.CheckBox();
            this.monitoredCurse2 = new System.Windows.Forms.CheckBox();
            this.monitoredCurse = new System.Windows.Forms.CheckBox();
            this.monitoredChoke = new System.Windows.Forms.CheckBox();
            this.monitoredChrDown = new System.Windows.Forms.CheckBox();
            this.monitoredBurn = new System.Windows.Forms.CheckBox();
            this.monitoredBlindness = new System.Windows.Forms.CheckBox();
            this.monitoredBio = new System.Windows.Forms.CheckBox();
            this.monitoredBind = new System.Windows.Forms.CheckBox();
            this.monitoredBane = new System.Windows.Forms.CheckBox();
            this.monitoredAttackDown = new System.Windows.Forms.CheckBox();
            this.monitoredAddle = new System.Windows.Forms.CheckBox();
            this.monitoredAccuracyDown = new System.Windows.Forms.CheckBox();
            this.monitoredAgiDown = new System.Windows.Forms.CheckBox();
            this.wakeSleepEnabled = new System.Windows.Forms.CheckBox();
            this.plDebuffWrapperPanel = new System.Windows.Forms.Panel();
            this.plDebuffPanel = new System.Windows.Forms.Panel();
            this.plAmnesia = new System.Windows.Forms.CheckBox();
            this.plDisease = new System.Windows.Forms.CheckBox();
            this.plWeight = new System.Windows.Forms.CheckBox();
            this.plVitDown = new System.Windows.Forms.CheckBox();
            this.plThrenody = new System.Windows.Forms.CheckBox();
            this.plSlow = new System.Windows.Forms.CheckBox();
            this.plSilence = new System.Windows.Forms.CheckBox();
            this.plShock = new System.Windows.Forms.CheckBox();
            this.plStrDown = new System.Windows.Forms.CheckBox();
            this.plRequiem = new System.Windows.Forms.CheckBox();
            this.plRasp = new System.Windows.Forms.CheckBox();
            this.plPoison = new System.Windows.Forms.CheckBox();
            this.plPlague = new System.Windows.Forms.CheckBox();
            this.plParalysis = new System.Windows.Forms.CheckBox();
            this.plMaxTpDown = new System.Windows.Forms.CheckBox();
            this.plMaxMpDown = new System.Windows.Forms.CheckBox();
            this.plMaxHpDown = new System.Windows.Forms.CheckBox();
            this.plMagicAtkDown = new System.Windows.Forms.CheckBox();
            this.plMagicAccDown = new System.Windows.Forms.CheckBox();
            this.plMndDown = new System.Windows.Forms.CheckBox();
            this.plIntDown = new System.Windows.Forms.CheckBox();
            this.plHelix = new System.Windows.Forms.CheckBox();
            this.plFrost = new System.Windows.Forms.CheckBox();
            this.plFlash = new System.Windows.Forms.CheckBox();
            this.plEvasionDown = new System.Windows.Forms.CheckBox();
            this.plElegy = new System.Windows.Forms.CheckBox();
            this.plDrown = new System.Windows.Forms.CheckBox();
            this.plDoom = new System.Windows.Forms.CheckBox();
            this.plDia = new System.Windows.Forms.CheckBox();
            this.plDefenseDown = new System.Windows.Forms.CheckBox();
            this.plDexDown = new System.Windows.Forms.CheckBox();
            this.plCurse2 = new System.Windows.Forms.CheckBox();
            this.plCurse = new System.Windows.Forms.CheckBox();
            this.plChoke = new System.Windows.Forms.CheckBox();
            this.plChrDown = new System.Windows.Forms.CheckBox();
            this.plBurn = new System.Windows.Forms.CheckBox();
            this.plBlindness = new System.Windows.Forms.CheckBox();
            this.plBio = new System.Windows.Forms.CheckBox();
            this.plBind = new System.Windows.Forms.CheckBox();
            this.plBane = new System.Windows.Forms.CheckBox();
            this.plAttackDown = new System.Windows.Forms.CheckBox();
            this.plAddle = new System.Windows.Forms.CheckBox();
            this.plAccuracyDown = new System.Windows.Forms.CheckBox();
            this.plAgiDown = new System.Windows.Forms.CheckBox();
            this.plSilenceItemEnabled = new System.Windows.Forms.CheckBox();
            this.monitoredDebuffEnabled = new System.Windows.Forms.CheckBox();
            this.plDebuffEnabled = new System.Windows.Forms.CheckBox();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.groupBox12 = new CurePlease.GroupBoxEx();
            this.requiredCuragaNumbers = new System.Windows.Forms.NumericUpDown();
            this.label31 = new System.Windows.Forms.Label();
            this.label29 = new System.Windows.Forms.Label();
            this.curagaTargetName = new System.Windows.Forms.TextBox();
            this.curagaTargetType = new System.Windows.Forms.ComboBox();
            this.label28 = new System.Windows.Forms.Label();
            this.curaga5Enabled = new System.Windows.Forms.CheckBox();
            this.curaga4Enabled = new System.Windows.Forms.CheckBox();
            this.curagaEnabled = new System.Windows.Forms.CheckBox();
            this.curaga2Enabled = new System.Windows.Forms.CheckBox();
            this.curaga3Enabled = new System.Windows.Forms.CheckBox();
            this.groupBox2 = new CurePlease.GroupBoxEx();
            this.groupBox35 = new CurePlease.GroupBoxEx();
            this.label62 = new System.Windows.Forms.Label();
            this.label60 = new System.Windows.Forms.Label();
            this.curePotency = new System.Windows.Forms.NumericUpDown();
            this.autoAdjust_Cure = new System.Windows.Forms.Button();
            this.cure6enabled = new System.Windows.Forms.CheckBox();
            this.cure5enabled = new System.Windows.Forms.CheckBox();
            this.cure3enabled = new System.Windows.Forms.CheckBox();
            this.cure4enabled = new System.Windows.Forms.CheckBox();
            this.cure2enabled = new System.Windows.Forms.CheckBox();
            this.cure1enabled = new System.Windows.Forms.CheckBox();
            this.regenGroupBox = new CurePlease.GroupBoxEx();
            this.cureBeforeRegen = new System.Windows.Forms.CheckBox();
            this.regen3 = new System.Windows.Forms.CheckBox();
            this.regen2 = new System.Windows.Forms.CheckBox();
            this.regen1 = new System.Windows.Forms.CheckBox();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.targetDebuffPage = new System.Windows.Forms.TabPage();
            this.targetDebuffsGroupBox = new CurePlease.GroupBoxEx();
            this.enableTargetDebuffsCheckBox = new System.Windows.Forms.CheckBox();
            this.targetDebuffHPLabel = new System.Windows.Forms.Label();
            this.targetDebuffHPPercentage = new System.Windows.Forms.NumericUpDown();
            this.targetDebuffsCheckedListBox = new System.Windows.Forms.CheckedListBox();

            ((System.ComponentModel.ISupportInitialize)(this.curagaCurePercentage)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.curaga5Amount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.curaga4Amount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.curaga3Amount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.curaga2Amount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.curagaAmount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.monitoredCurePercentage)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.fullCureamount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.priorityCurePercentage)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cure6amount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cure5amount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.curePercentage)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cure4amount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cure3amount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cure2amount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cure1amount)).BeginInit();
            this.groupBox16.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.healWhenMPBelow)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.standAtMP_Percentage)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.mpMintempitemusage)).BeginInit();
            this.tabPage7.SuspendLayout();
            this.groupBoxEx1.SuspendLayout();
            this.panel15.SuspendLayout();
            this.groupBox18.SuspendLayout();
            this.groupBox17.SuspendLayout();
            this.groupBox14.SuspendLayout();
            this.panel9.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.autoFollowDistance)).BeginInit();
            this.groupBox13.SuspendLayout();
            this.tabPage5.SuspendLayout();
            this.groupBox10.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.TargetRemoval_Delay)).BeginInit();
            this.groupBox36.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.RadialArcanaMP)).BeginInit();
            this.groupBox15.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.DevotionMP)).BeginInit();
            this.Raise.SuspendLayout();
            this.groupBox33.SuspendLayout();
            this.groupBox32.SuspendLayout();
            this.groupBox29.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.sublimationMP)).BeginInit();
            this.groupBox11.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ConvertMP)).BeginInit();
            this.groupBox4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.mpMinCastValue)).BeginInit();
            this.tabPage3.SuspendLayout();
            this.groupBox24.SuspendLayout();
            this.groupBox8.SuspendLayout();
            this.rdmJAgroup.SuspendLayout();
            this.schJAgroup.SuspendLayout();
            this.whmJAgroup.SuspendLayout();
            this.tabPage8.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.recastSong)).BeginInit();
            this.panel7.SuspendLayout();
            this.panel8.SuspendLayout();
            this.groupBox30.SuspendLayout();
            this.groupBox31.SuspendLayout();
            this.groupBox28.SuspendLayout();
            this.groupBox20.SuspendLayout();
            this.groupBox23.SuspendLayout();
            this.groupBox22.SuspendLayout();
            this.groupBox21.SuspendLayout();
            this.groupBox19.SuspendLayout();
            this.tabPage6.SuspendLayout();
            this.groupBox7.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.tabControl2.SuspendLayout();
            this.tabPage9.SuspendLayout();
            this.groupBox34.SuspendLayout();
            this.groupBox9.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.plProtectralevel)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.plShellralevel)).BeginInit();
            this.groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.autoAdloquium_Minutes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoStormspellMinutes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoRegen_Minutes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoProtect_Minutes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoShell_Minutes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoRefresh_Minutes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoPhalanxIIMinutes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoHasteMinutes)).BeginInit();
            this.plBuffGroup.SuspendLayout();
            this.panel14.SuspendLayout();
            this.panel12.SuspendLayout();
            this.panel5.SuspendLayout();
            this.panel4.SuspendLayout();
            this.panel3.SuspendLayout();
            this.tabPage10.SuspendLayout();
            this.groupBox27.SuspendLayout();
            this.panel13.SuspendLayout();
            this.groupBox26.SuspendLayout();
            this.groupBox25.SuspendLayout();
            this.tabPage4.SuspendLayout();
            this.panel10.SuspendLayout();
            this.panel11.SuspendLayout();
            this.panel6.SuspendLayout();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.plDebuffWrapperPanel.SuspendLayout();
            this.plDebuffPanel.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.groupBox12.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.requiredCuragaNumbers)).EndInit();
            this.groupBox2.SuspendLayout();
            this.groupBox35.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.curePotency)).EndInit();
            this.tabControl1.SuspendLayout();
            this.targetDebuffPage.SuspendLayout();
            this.targetDebuffsGroupBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.targetDebuffHPPercentage)).BeginInit();
            this.regenGroupBox.SuspendLayout();
            this.SuspendLayout();
            //
            // regenGroupBox
            //
            this.regenGroupBox.Controls.Add(this.cureBeforeRegen);
            this.regenGroupBox.Controls.Add(this.regen3);
            this.regenGroupBox.Controls.Add(this.regen2);
            this.regenGroupBox.Controls.Add(this.regen1);
            this.regenGroupBox.Location = new System.Drawing.Point(172, 103);
            this.regenGroupBox.Name = "regenGroupBox";
            this.regenGroupBox.Size = new System.Drawing.Size(200, 125);
            this.regenGroupBox.TabIndex = 15;
            this.regenGroupBox.TabStop = false;
            this.regenGroupBox.Text = "Regen";
            //
            // cureBeforeRegen
            //
            this.cureBeforeRegen.AutoSize = true;
            this.cureBeforeRegen.Location = new System.Drawing.Point(6, 95);
            this.cureBeforeRegen.Name = "cureBeforeRegen";
            this.cureBeforeRegen.Size = new System.Drawing.Size(126, 19);
            this.cureBeforeRegen.TabIndex = 3;
            this.cureBeforeRegen.Text = "Cure before Regen";
            this.cureBeforeRegen.UseVisualStyleBackColor = true;
            //
            // regen3
            //
            this.regen3.AutoSize = true;
            this.regen3.Location = new System.Drawing.Point(6, 70);
            this.regen3.Name = "regen3";
            this.regen3.Size = new System.Drawing.Size(75, 19);
            this.regen3.TabIndex = 2;
            this.regen3.Text = "Regen III";
            this.regen3.UseVisualStyleBackColor = true;
            //
            // regen2
            //
            this.regen2.AutoSize = true;
            this.regen2.Location = new System.Drawing.Point(6, 45);
            this.regen2.Name = "regen2";
            this.regen2.Size = new System.Drawing.Size(72, 19);
            this.regen2.TabIndex = 1;
            this.regen2.Text = "Regen II";
            this.regen2.UseVisualStyleBackColor = true;
            //
            // regen1
            //
            this.regen1.AutoSize = true;
            this.regen1.Location = new System.Drawing.Point(6, 20);
            this.regen1.Name = "regen1";
            this.regen1.Size = new System.Drawing.Size(63, 19);
            this.regen1.TabIndex = 0;
            this.regen1.Text = "Regen";
            this.regen1.UseVisualStyleBackColor = true;
            //
            // Form2
            //
            this.targetDebuffsGroupBox.ResumeLayout(false);
            this.targetDebuffsGroupBox.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.targetDebuffHPPercentage)).EndInit();
            this.regenGroupBox.ResumeLayout(false);
            this.regenGroupBox.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion
        private System.Windows.Forms.Button button4;
        private System.Windows.Forms.ToolTip toolTip1;
        private System.Windows.Forms.Button saveAsButton;
        private System.Windows.Forms.Button loadButton;
        private System.Windows.Forms.CheckBox loadJobSettings;
        private System.Windows.Forms.OpenFileDialog openFileDialog1;
        private System.Windows.Forms.Timer timer1;
        private System.Windows.Forms.TabPage tabPage7;
        private System.Windows.Forms.TextBox listeningPort;
        private System.Windows.Forms.Label label48;
        private System.Windows.Forms.TextBox ipAddress;
        private System.Windows.Forms.Label label38;
        private System.Windows.Forms.Label label61;
        private System.Windows.Forms.CheckBox trackCastingPackets;
        private System.Windows.Forms.Label label24;
        private System.Windows.Forms.CheckBox enableFastCast_Mode;
        private System.Windows.Forms.CheckBox FFXIDefaultAutoFollow;
        private System.Windows.Forms.Panel panel9;
        private System.Windows.Forms.Label label56;
        private System.Windows.Forms.CheckBox autoFollow_Warning;
        private System.Windows.Forms.CheckBox checkBox4;
        private System.Windows.Forms.TextBox autoFollowName;
        private System.Windows.Forms.NumericUpDown autoFollowDistance;
        private System.Windows.Forms.Label label33;
        private System.Windows.Forms.Label label32;
        private System.Windows.Forms.CheckBox pauseOnKO;
        private System.Windows.Forms.CheckBox MinimiseonStart;
        private System.Windows.Forms.CheckBox pauseOnStartBox;
        private System.Windows.Forms.CheckBox pauseOnZoneBox;
        private System.Windows.Forms.TabPage tabPage5;
        private System.Windows.Forms.CheckBox DisableTargettingCancel;
        private System.Windows.Forms.Label label27;
        private System.Windows.Forms.ComboBox RadialArcanaSpell;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.NumericUpDown RadialArcanaMP;
        private System.Windows.Forms.CheckBox Fullcircle_GEOTarget;
        private System.Windows.Forms.CheckBox Fullcircle_DisableEnemy;
        private System.Windows.Forms.CheckBox AssistSpecifiedTarget;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox autoTarget_target;
        private System.Windows.Forms.Label label37;
        private System.Windows.Forms.Label label36;
        private System.Windows.Forms.ComboBox Hate_SpellType;
        private System.Windows.Forms.CheckBox autoTarget;
        private System.Windows.Forms.TextBox autoTargetSpell;
        private System.Windows.Forms.CheckBox DevotionWhenEngaged;
        private System.Windows.Forms.TextBox DevotionTargetName;
        private System.Windows.Forms.ComboBox DevotionTargetType;
        private System.Windows.Forms.Label label34;
        private System.Windows.Forms.Label label35;
        private System.Windows.Forms.NumericUpDown DevotionMP;
        private System.Windows.Forms.CheckBox acceptRaiseOnlyWhenNotInCombat;
        private System.Windows.Forms.CheckBox acceptRaise;
        private System.Windows.Forms.Label label25;
        private System.Windows.Forms.CheckBox enableAddOn;
        private System.Windows.Forms.CheckBox OvercureOnHighPriority;
        private System.Windows.Forms.CheckBox enableMonitoredPriority;
        private System.Windows.Forms.CheckBox Undercure;
        private System.Windows.Forms.CheckBox Overcure;
        private System.Windows.Forms.Label label51;
        private System.Windows.Forms.NumericUpDown sublimationMP;
        private System.Windows.Forms.Label label26;
        private System.Windows.Forms.NumericUpDown ConvertMP;
        private System.Windows.Forms.NumericUpDown healWhenMPBelow;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.NumericUpDown standAtMP_Percentage;
        private System.Windows.Forms.CheckBox standAtMP;
        private System.Windows.Forms.CheckBox healLowMP;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.NumericUpDown mpMintempitemusage;
        private System.Windows.Forms.CheckBox lowMPcheckBox;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.NumericUpDown mpMinCastValue;
        private System.Windows.Forms.TabPage tabPage3;
        private System.Windows.Forms.CheckBox marcato;
        private System.Windows.Forms.CheckBox troubadour;
        private System.Windows.Forms.CheckBox nightingale;
        private System.Windows.Forms.CheckBox pianissimo;
        private System.Windows.Forms.CheckBox LifeCycleBox;
        private System.Windows.Forms.CheckBox EclipticAttritionBox;
        private System.Windows.Forms.CheckBox FullCircleBox;
        private System.Windows.Forms.CheckBox RadialArcanaBox;
        private System.Windows.Forms.CheckBox BlazeOfGloryBox;
        private System.Windows.Forms.CheckBox DematerializeBox;
        private System.Windows.Forms.CheckBox EntrustBox;
        private System.Windows.Forms.CheckBox composure;
        private System.Windows.Forms.CheckBox convert;
        private System.Windows.Forms.CheckBox addBlack;
        private System.Windows.Forms.CheckBox darkArts;
        private System.Windows.Forms.CheckBox sublimation;
        private System.Windows.Forms.CheckBox perpetuance;
        private System.Windows.Forms.CheckBox rapture;
        private System.Windows.Forms.CheckBox accession;
        private System.Windows.Forms.CheckBox celerity;
        private System.Windows.Forms.CheckBox penury;
        private System.Windows.Forms.CheckBox addWhite;
        private System.Windows.Forms.CheckBox lightArts;
        private System.Windows.Forms.CheckBox DivineCaressBox;
        private System.Windows.Forms.CheckBox DevotionBox;
        private System.Windows.Forms.CheckBox divineSealBox;
        private System.Windows.Forms.CheckBox afflatusMisery;
        private System.Windows.Forms.CheckBox afflatusSolace;
        private System.Windows.Forms.TabPage tabPage8;
        private System.Windows.Forms.CheckBox recastSongs_monitored;
        private System.Windows.Forms.CheckBox SongsOnlyWhenNearEngaged;
        private System.Windows.Forms.Label label50;
        private System.Windows.Forms.CheckBox enableSinging;
        private System.Windows.Forms.ComboBox song3;
        private System.Windows.Forms.ComboBox dummy1;
        private System.Windows.Forms.Label label43;
        private System.Windows.Forms.Label label44;
        private System.Windows.Forms.Label label40;
        private System.Windows.Forms.NumericUpDown recastSong;
        private System.Windows.Forms.Label label39;
        private System.Windows.Forms.ComboBox clarionSong;
        private System.Windows.Forms.Label label47;
        private System.Windows.Forms.Panel panel7;
        private System.Windows.Forms.Panel panel8;
        private System.Windows.Forms.ComboBox comboBox3;
        private System.Windows.Forms.Label label53;
        private System.Windows.Forms.ComboBox comboBox4;
        private System.Windows.Forms.Label label54;
        private System.Windows.Forms.ComboBox comboBox1;
        private System.Windows.Forms.Label label49;
        private System.Windows.Forms.ComboBox comboBox2;
        private System.Windows.Forms.Label label52;
        private System.Windows.Forms.ComboBox song4;
        private System.Windows.Forms.ComboBox dummy2;
        private System.Windows.Forms.Label label42;
        private System.Windows.Forms.Label label41;
        private System.Windows.Forms.ComboBox song2;
        private System.Windows.Forms.Label label46;
        private System.Windows.Forms.ComboBox song1;
        private System.Windows.Forms.Label label45;
        private System.Windows.Forms.TabPage tabPage6;
        private System.Windows.Forms.CheckBox specifiedEngageTarget;
        private System.Windows.Forms.CheckBox GeoAOE_Engaged;
        private System.Windows.Forms.CheckBox EnableLuopanSpells;
        private System.Windows.Forms.CheckBox GEO_engaged;
        private System.Windows.Forms.CheckBox EnableGeoSpells;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.TextBox entrustSpell_target;
        private System.Windows.Forms.ListBox entrustINDISpell;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.TextBox GEOSpell_target;
        private System.Windows.Forms.ListBox GEOSpell;
        private System.Windows.Forms.ListBox INDISpell;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.TabControl tabControl2;
        private System.Windows.Forms.TabPage tabPage9;
        private System.Windows.Forms.CheckBox plUtsusemi;
        private System.Windows.Forms.CheckBox AOE_Barstatus;
        private System.Windows.Forms.CheckBox AOE_Barelemental;
        private System.Windows.Forms.CheckBox plAuspice;
        private System.Windows.Forms.ComboBox plBarStatus_Spell;
        private System.Windows.Forms.CheckBox plGainBoost;
        private System.Windows.Forms.CheckBox plBarStatus;
        private System.Windows.Forms.ComboBox plGainBoost_spell;
        private System.Windows.Forms.ComboBox plBarElement_Spell;
        private System.Windows.Forms.CheckBox plBarElement;
        private System.Windows.Forms.NumericUpDown plProtectralevel;
        private System.Windows.Forms.CheckBox plShellra;
        private System.Windows.Forms.NumericUpDown plShellralevel;
        private System.Windows.Forms.CheckBox plProtectra;
        private System.Windows.Forms.Label label63;
        private System.Windows.Forms.ComboBox autoStorm;
        private System.Windows.Forms.Label label64;
        private System.Windows.Forms.Label label65;
        private System.Windows.Forms.NumericUpDown autoStormspellMinutes;
        private System.Windows.Forms.Label label21;
        private System.Windows.Forms.ComboBox autoRegen;
        private System.Windows.Forms.Label label22;
        private System.Windows.Forms.Label label23;
        private System.Windows.Forms.NumericUpDown autoRegen_Minutes;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.ComboBox autoProtect;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.Label label20;
        private System.Windows.Forms.NumericUpDown autoProtect_Minutes;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.ComboBox autoShell;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.NumericUpDown autoShell_Minutes;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.ComboBox autoRefresh;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label autoRefreshLabel;
        private System.Windows.Forms.NumericUpDown autoRefresh_Minutes;
        private System.Windows.Forms.NumericUpDown autoPhalanxIIMinutes;
        private System.Windows.Forms.NumericUpDown autoHasteMinutes;
        private System.Windows.Forms.Label autoPhalanxIILabel;
        private System.Windows.Forms.Label autoHasteLabel;
        private System.Windows.Forms.Panel panel12;
        private System.Windows.Forms.RadioButton plRegenLevel5;
        private System.Windows.Forms.CheckBox plRegen;
        private System.Windows.Forms.RadioButton plRegenLevel1;
        private System.Windows.Forms.RadioButton plRegenLevel4;
        private System.Windows.Forms.RadioButton plRegenLevel2;
        private System.Windows.Forms.RadioButton plRegenLevel3;
        private System.Windows.Forms.CheckBox plAdloquium;
        private System.Windows.Forms.CheckBox plShell;
        private System.Windows.Forms.CheckBox plProtect;
        private System.Windows.Forms.CheckBox plAquaveil;
        private System.Windows.Forms.ComboBox plStormSpell_Spell;
        private System.Windows.Forms.CheckBox plStormSpell;
        private System.Windows.Forms.CheckBox plKlimaform;
        private System.Windows.Forms.ComboBox plEnspell_spell;
        private System.Windows.Forms.CheckBox plEnspell;
        private System.Windows.Forms.Panel panel5;
        private System.Windows.Forms.CheckBox plTemper;
        private System.Windows.Forms.RadioButton plTemperLevel1;
        private System.Windows.Forms.RadioButton plTemperLevel2;
        private System.Windows.Forms.Panel panel4;
        private System.Windows.Forms.CheckBox plRefresh;
        private System.Windows.Forms.RadioButton plRefreshLevel3;
        private System.Windows.Forms.RadioButton plRefreshLevel1;
        private System.Windows.Forms.RadioButton plRefreshLevel2;
        private System.Windows.Forms.CheckBox plPhalanx;
        private System.Windows.Forms.Panel panel3;
        private System.Windows.Forms.CheckBox plReraise;
        private System.Windows.Forms.RadioButton plReraiseLevel1;
        private System.Windows.Forms.RadioButton plReraiseLevel4;
        private System.Windows.Forms.RadioButton plReraiseLevel2;
        private System.Windows.Forms.RadioButton plReraiseLevel3;
        private System.Windows.Forms.CheckBox plBlink;
        private System.Windows.Forms.CheckBox plStoneskin;
        private System.Windows.Forms.TabPage tabPage10;
        private System.Windows.Forms.CheckBox regenPerpetuance;
        private System.Windows.Forms.CheckBox regenAccession;
        private System.Windows.Forms.CheckBox adloquiumPerpetuance;
        private System.Windows.Forms.CheckBox adloquiumAccession;
        private System.Windows.Forms.CheckBox barstatusPerpetuance;
        private System.Windows.Forms.CheckBox barspellPerpetuance;
        private System.Windows.Forms.CheckBox aquaveilPerpetuance;
        private System.Windows.Forms.CheckBox stormspellPerpetuance;
        private System.Windows.Forms.CheckBox enspellPerpetuance;
        private System.Windows.Forms.CheckBox stoneskinPerpetuance;
        private System.Windows.Forms.CheckBox phalanxPerpetuance;
        private System.Windows.Forms.CheckBox blinkPerpetuance;
        private System.Windows.Forms.CheckBox refreshPerpetuance;
        private System.Windows.Forms.CheckBox barstatusAccession;
        private System.Windows.Forms.CheckBox barspellAccession;
        private System.Windows.Forms.CheckBox refreshAccession;
        private System.Windows.Forms.CheckBox aquaveilAccession;
        private System.Windows.Forms.CheckBox stormspellAccession;
        private System.Windows.Forms.CheckBox enspellAccession;
        private System.Windows.Forms.CheckBox phalanxAccession;
        private System.Windows.Forms.CheckBox blinkAccession;
        private System.Windows.Forms.CheckBox stoneskinAccession;
        private System.Windows.Forms.CheckBox EnlightenmentReraise;
        private System.Windows.Forms.CheckBox perpetuanceRegen;
        private System.Windows.Forms.CheckBox accessionProShell;
        private System.Windows.Forms.CheckBox accessionRegen;
        private System.Windows.Forms.CheckBox accessionCure;
        private System.Windows.Forms.TabPage tabPage4;
        private System.Windows.Forms.Label label57;
        private System.Windows.Forms.Panel panel10;
        private System.Windows.Forms.Panel panel11;
        private System.Windows.Forms.CheckBox na_MagicDefenseDown;
        private System.Windows.Forms.CheckBox na_Weight;
        private System.Windows.Forms.CheckBox na_VitDown;
        private System.Windows.Forms.CheckBox na_Threnody;
        private System.Windows.Forms.CheckBox na_Slow;
        private System.Windows.Forms.CheckBox na_Shock;
        private System.Windows.Forms.CheckBox na_StrDown;
        private System.Windows.Forms.CheckBox na_Requiem;
        private System.Windows.Forms.CheckBox na_Rasp;
        private System.Windows.Forms.CheckBox na_MaxTpDown;
        private System.Windows.Forms.CheckBox na_MaxMpDown;
        private System.Windows.Forms.CheckBox na_MaxHpDown;
        private System.Windows.Forms.CheckBox na_MagicAttackDown;
        private System.Windows.Forms.CheckBox na_MagicAccDown;
        private System.Windows.Forms.CheckBox na_MndDown;
        private System.Windows.Forms.CheckBox na_IntDown;
        private System.Windows.Forms.CheckBox na_Helix;
        private System.Windows.Forms.CheckBox na_Frost;
        private System.Windows.Forms.CheckBox na_EvasionDown;
        private System.Windows.Forms.CheckBox na_Elegy;
        private System.Windows.Forms.CheckBox na_Drown;
        private System.Windows.Forms.CheckBox na_Dia;
        private System.Windows.Forms.CheckBox na_DefenseDown;
        private System.Windows.Forms.CheckBox na_DexDown;
        private System.Windows.Forms.CheckBox na_Choke;
        private System.Windows.Forms.CheckBox na_ChrDown;
        private System.Windows.Forms.CheckBox na_Burn;
        private System.Windows.Forms.CheckBox na_Bio;
        private System.Windows.Forms.CheckBox na_Bind;
        private System.Windows.Forms.CheckBox na_AttackDown;
        private System.Windows.Forms.CheckBox na_Addle;
        private System.Windows.Forms.CheckBox na_AccuracyDown;
        private System.Windows.Forms.CheckBox na_AgiDown;
        private System.Windows.Forms.CheckBox PrioritiseOverLowerTier;
        private System.Windows.Forms.CheckBox SpecifiednaSpellsenable;
        private System.Windows.Forms.Panel panel6;
        private System.Windows.Forms.CheckBox naErase;
        private System.Windows.Forms.CheckBox naBlindness;
        private System.Windows.Forms.CheckBox naPoison;
        private System.Windows.Forms.CheckBox naDisease;
        private System.Windows.Forms.CheckBox naParalysis;
        private System.Windows.Forms.CheckBox naPetrification;
        private System.Windows.Forms.CheckBox naSilence;
        private System.Windows.Forms.CheckBox naCurse;
        private System.Windows.Forms.CheckBox naPlague;
        private System.Windows.Forms.CheckBox naSpellsenable;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.CheckBox plDoomEnabled;
        private System.Windows.Forms.ComboBox plDoomitem;
        private System.Windows.Forms.ComboBox wakeSleepSpell;
        private System.Windows.Forms.ComboBox plSilenceItem;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.CheckBox monitoredDisease;
        private System.Windows.Forms.CheckBox monitoredWeight;
        private System.Windows.Forms.CheckBox monitoredVitDown;
        private System.Windows.Forms.CheckBox monitoredThrenody;
        private System.Windows.Forms.CheckBox monitoredSlow;
        private System.Windows.Forms.CheckBox monitoredSleep2;
        private System.Windows.Forms.CheckBox monitoredSleep;
        private System.Windows.Forms.CheckBox monitoredSilence;
        private System.Windows.Forms.CheckBox monitoredShock;
        private System.Windows.Forms.CheckBox monitoredStrDown;
        private System.Windows.Forms.CheckBox monitoredRequiem;
        private System.Windows.Forms.CheckBox monitoredRasp;
        private System.Windows.Forms.CheckBox monitoredPoison;
        private System.Windows.Forms.CheckBox monitoredPlague;
        private System.Windows.Forms.CheckBox monitoredPetrification;
        private System.Windows.Forms.CheckBox monitoredParalysis;
        private System.Windows.Forms.CheckBox monitoredMaxTpDown;
        private System.Windows.Forms.CheckBox monitoredMaxMpDown;
        private System.Windows.Forms.CheckBox monitoredMaxHpDown;
        private System.Windows.Forms.CheckBox monitoredMagicAtkDown;
        private System.Windows.Forms.CheckBox monitoredMagicAccDown;
        private System.Windows.Forms.CheckBox monitoredMndDown;
        private System.Windows.Forms.CheckBox monitoredIntDown;
        private System.Windows.Forms.CheckBox monitoredHelix;
        private System.Windows.Forms.CheckBox monitoredFrost;
        private System.Windows.Forms.CheckBox monitoredFlash;
        private System.Windows.Forms.CheckBox monitoredEvasionDown;
        private System.Windows.Forms.CheckBox monitoredElegy;
        private System.Windows.Forms.CheckBox monitoredDrown;
        private System.Windows.Forms.CheckBox monitoredDoom;
        private System.Windows.Forms.CheckBox monitoredDia;
        private System.Windows.Forms.CheckBox monitoredDefenseDown;
        private System.Windows.Forms.CheckBox monitoredDexDown;
        private System.Windows.Forms.CheckBox monitoredCurse2;
        private System.Windows.Forms.CheckBox monitoredCurse;
        private System.Windows.Forms.CheckBox monitoredChoke;
        private System.Windows.Forms.CheckBox monitoredChrDown;
        private System.Windows.Forms.CheckBox monitoredBurn;
        private System.Windows.Forms.CheckBox monitoredBlindness;
        private System.Windows.Forms.CheckBox monitoredBio;
        private System.Windows.Forms.CheckBox monitoredBind;
        private System.Windows.Forms.CheckBox monitoredBane;
        private System.Windows.Forms.CheckBox monitoredAttackDown;
        private System.Windows.Forms.CheckBox monitoredAddle;
        private System.Windows.Forms.CheckBox monitoredAccuracyDown;
        private System.Windows.Forms.CheckBox monitoredAgiDown;
        private System.Windows.Forms.CheckBox wakeSleepEnabled;
        private System.Windows.Forms.Panel plDebuffWrapperPanel;
        private System.Windows.Forms.Panel plDebuffPanel;
        private System.Windows.Forms.CheckBox plDisease;
        private System.Windows.Forms.CheckBox plWeight;
        private System.Windows.Forms.CheckBox plVitDown;
        private System.Windows.Forms.CheckBox plThrenody;
        private System.Windows.Forms.CheckBox plSlow;
        private System.Windows.Forms.CheckBox plSilence;
        private System.Windows.Forms.CheckBox plShock;
        private System.Windows.Forms.CheckBox plStrDown;
        private System.Windows.Forms.CheckBox plRequiem;
        private System.Windows.Forms.CheckBox plRasp;
        private System.Windows.Forms.CheckBox plPoison;
        private System.Windows.Forms.CheckBox plPlague;
        private System.Windows.Forms.CheckBox plParalysis;
        private System.Windows.Forms.CheckBox plMaxTpDown;
        private System.Windows.Forms.CheckBox plMaxMpDown;
        private System.Windows.Forms.CheckBox plMaxHpDown;
        private System.Windows.Forms.CheckBox plMagicAtkDown;
        private System.Windows.Forms.CheckBox plMagicAccDown;
        private System.Windows.Forms.CheckBox plMndDown;
        private System.Windows.Forms.CheckBox plIntDown;
        private System.Windows.Forms.CheckBox plHelix;
        private System.Windows.Forms.CheckBox plFrost;
        private System.Windows.Forms.CheckBox plFlash;
        private System.Windows.Forms.CheckBox plEvasionDown;
        private System.Windows.Forms.CheckBox plElegy;
        private System.Windows.Forms.CheckBox plDrown;
        private System.Windows.Forms.CheckBox plDoom;
        private System.Windows.Forms.CheckBox plDia;
        private System.Windows.Forms.CheckBox plDefenseDown;
        private System.Windows.Forms.CheckBox plDexDown;
        private System.Windows.Forms.CheckBox plCurse2;
        private System.Windows.Forms.CheckBox plCurse;
        private System.Windows.Forms.CheckBox plChoke;
        private System.Windows.Forms.CheckBox plChrDown;
        private System.Windows.Forms.CheckBox plBurn;
        private System.Windows.Forms.CheckBox plBlindness;
        private System.Windows.Forms.CheckBox plBio;
        private System.Windows.Forms.CheckBox plBind;
        private System.Windows.Forms.CheckBox plBane;
        private System.Windows.Forms.CheckBox plAttackDown;
        private System.Windows.Forms.CheckBox plAddle;
        private System.Windows.Forms.CheckBox plAccuracyDown;
        private System.Windows.Forms.CheckBox plAgiDown;
        private System.Windows.Forms.CheckBox plSilenceItemEnabled;
        private System.Windows.Forms.CheckBox monitoredDebuffEnabled;
        private System.Windows.Forms.CheckBox plDebuffEnabled;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.NumericUpDown requiredCuragaNumbers;
        private System.Windows.Forms.Label label31;
        private System.Windows.Forms.Label label29;
        private System.Windows.Forms.TextBox curagaTargetName;
        private System.Windows.Forms.ComboBox curagaTargetType;
        private System.Windows.Forms.Label label28;
        private System.Windows.Forms.Label curagaPercentageValueLabel;
        private System.Windows.Forms.TrackBar curagaCurePercentage;
        private System.Windows.Forms.Label label30;
        private System.Windows.Forms.NumericUpDown curaga5Amount;
        private System.Windows.Forms.NumericUpDown curaga4Amount;
        private System.Windows.Forms.NumericUpDown curaga3Amount;
        private System.Windows.Forms.NumericUpDown curaga2Amount;
        private System.Windows.Forms.NumericUpDown curagaAmount;
        private System.Windows.Forms.CheckBox curaga5Enabled;
        private System.Windows.Forms.CheckBox curaga4Enabled;
        private System.Windows.Forms.CheckBox curagaEnabled;
        private System.Windows.Forms.CheckBox curaga2Enabled;
        private System.Windows.Forms.CheckBox curaga3Enabled;
        private System.Windows.Forms.Label label62;
        private System.Windows.Forms.Label label60;
        private System.Windows.Forms.NumericUpDown curePotency;
        private System.Windows.Forms.Button autoAdjust_Cure;
        private System.Windows.Forms.TrackBar monitoredCurePercentage;
        private System.Windows.Forms.Label label55;
        private System.Windows.Forms.Label monitoredCurePercentageValueLabel;
        private System.Windows.Forms.CheckBox fullCureenabled;
        private System.Windows.Forms.NumericUpDown fullCureamount;
        private System.Windows.Forms.TrackBar priorityCurePercentage;
        private System.Windows.Forms.Label priorityCurePercentageLabel;
        private System.Windows.Forms.CheckBox cure6enabled;
        private System.Windows.Forms.NumericUpDown cure6amount;
        private System.Windows.Forms.CheckBox cure5enabled;
        private System.Windows.Forms.Label priorityCurePercentageValueLabel;
        private System.Windows.Forms.CheckBox cure3enabled;
        private System.Windows.Forms.CheckBox cure4enabled;
        private System.Windows.Forms.NumericUpDown cure5amount;
        private System.Windows.Forms.TrackBar curePercentage;
        private System.Windows.Forms.CheckBox cure2enabled;
        private System.Windows.Forms.NumericUpDown cure4amount;
        private System.Windows.Forms.CheckBox cure1enabled;
        private System.Windows.Forms.Label curePercentageValueLabel;
        private System.Windows.Forms.NumericUpDown cure3amount;
        private System.Windows.Forms.Label curePercentageLabel;
        private System.Windows.Forms.NumericUpDown cure2amount;
        private System.Windows.Forms.NumericUpDown cure1amount;
        public System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.Label label59;
        private System.Windows.Forms.NumericUpDown TargetRemoval_Delay;
        private System.Windows.Forms.Label label58;
        private GroupBoxEx groupBox18;
        private GroupBoxEx groupBox17;
        private GroupBoxEx groupBox14;
        private GroupBoxEx groupBox13;
        private GroupBoxEx groupBox10;
        private GroupBoxEx groupBox36;
        private GroupBoxEx groupBox16;
        private GroupBoxEx groupBox15;
        private GroupBoxEx Raise;
        private GroupBoxEx groupBox33;
        private GroupBoxEx groupBox32;
        private GroupBoxEx groupBox29;
        private GroupBoxEx groupBox11;
        private GroupBoxEx groupBox4;
        private GroupBoxEx groupBox24;
        private GroupBoxEx groupBox8;
        private GroupBoxEx rdmJAgroup;
        private GroupBoxEx schJAgroup;
        private GroupBoxEx whmJAgroup;
        private GroupBoxEx groupBox28;
        private GroupBoxEx groupBox20;
        private GroupBoxEx groupBox23;
        private GroupBoxEx groupBox30;
        private GroupBoxEx groupBox31;
        private GroupBoxEx groupBox22;
        private GroupBoxEx groupBox21;
        private GroupBoxEx groupBox19;
        private GroupBoxEx groupBox7;
        private GroupBoxEx groupBox6;
        private GroupBoxEx groupBox5;
        private GroupBoxEx groupBox34;
        private GroupBoxEx groupBox9;
        private GroupBoxEx groupBox1;
        private GroupBoxEx plBuffGroup;
        private GroupBoxEx groupBox27;
        private GroupBoxEx groupBox26;
        private GroupBoxEx groupBox25;
        private GroupBoxEx groupBox12;
        private GroupBoxEx groupBox2;
        private GroupBoxEx groupBox35;
        private System.Windows.Forms.Panel panel13;
        private System.Windows.Forms.Label label66;
        private System.Windows.Forms.Panel panel14;
        private System.Windows.Forms.CheckBox plHaste;
        private System.Windows.Forms.RadioButton plHasteLevel1;
        private System.Windows.Forms.RadioButton plHasteLevel2;
        private System.Windows.Forms.CheckBox enableOutOfPartyHealing;
        private GroupBoxEx groupBoxEx1;
        private System.Windows.Forms.CheckBox enableHotKeys;
        private System.Windows.Forms.Panel panel15;
        private System.Windows.Forms.Label label67;
        private System.Windows.Forms.CheckBox EsunaOnlyAmnesia;
        private System.Windows.Forms.CheckBox Esuna;
        private System.Windows.Forms.Label label68;
        private System.Windows.Forms.NumericUpDown autoAdloquium_Minutes;
        private System.Windows.Forms.Label label69;
        private System.Windows.Forms.CheckBox monitoredAmnesia;
        private System.Windows.Forms.CheckBox plAmnesia;
        private System.Windows.Forms.ComboBox plSpikes_Spell;
        private System.Windows.Forms.CheckBox plSpikes;
        private GroupBoxEx regenGroupBox;
        private System.Windows.Forms.CheckBox cureBeforeRegen;
        private System.Windows.Forms.CheckBox regen3;
        private System.Windows.Forms.CheckBox regen2;
        private System.Windows.Forms.CheckBox regen1;
        private System.Windows.Forms.CheckedListBox targetDebuffsCheckedListBox;
        private System.Windows.Forms.NumericUpDown targetDebuffHPPercentage;
        private System.Windows.Forms.Label targetDebuffHPLabel;
        private System.Windows.Forms.CheckBox enableTargetDebuffsCheckBox;
    }
}